import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#050E1D" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.1)",
  },
  logoContainer: { flexDirection: "row", alignItems: "center" },
  logo: {
    width: 100,
    height: 100,
    resizeMode: "contain",
  },
  notification: {
    position: "relative",
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: "#ff4757",
    borderRadius: 8,
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: { color: "#fff", fontSize: 10, fontWeight: "bold" },
  contentArea: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 40 },
  pageTitle: {
    color: "#FFF",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 20,
  },
  label: { color: "#7C8DB5", fontSize: 13, marginBottom: 6 },
  input: {
    backgroundColor: "#101D33",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(22,199,231,0.3)",
    color: "#FFF",
    paddingHorizontal: 14,
    height: 48,
    marginBottom: 16,
    fontSize: 15,
  },
  textArea: { height: 100, textAlignVertical: "top", paddingTop: 12 },
  tipoRow: { flexDirection: "row", gap: 8, marginBottom: 16, flexWrap: "wrap" },
  tipoButton: {
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  tipoButtonText: { color: "#7C8DB5", fontSize: 12, fontWeight: "700" },
  pickerFake: {
    backgroundColor: "#101D33",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(22,199,231,0.3)",
    height: 48,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  pickerFakeText: { color: "#FFF", fontSize: 15 },
  btnSubmit: {
    backgroundColor: "#00d2b4",
    height: 52,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 32,
    flexDirection: "row",
    gap: 8,
  },
  btnSubmitText: { color: "#050E1D", fontSize: 16, fontWeight: "700" },
  sectionTitle: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 14,
  },
  cardEvento: {
    backgroundColor: "#101D33",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(22,199,231,0.1)",
  },
  tipoBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    borderWidth: 1,
  },
  tipoBadgeText: { fontSize: 11, fontWeight: "700" },
  cardData: { color: "#5D708A", fontSize: 12, flex: 1 },
  btnDelete: { padding: 4 },
  cardTitulo: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  cardDesc: { color: "#7C8DB5", fontSize: 13, marginBottom: 6 },
  cardMeta: { color: "#3B4A61", fontSize: 12 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalBox: {
    backgroundColor: "#101D33",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "55%",
    paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  modalTitle: { color: "#FFF", fontSize: 17, fontWeight: "700" },
  modalItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.04)",
  },
  modalItemText: { color: "#FFF", fontSize: 15 },
  emptyText: { color: "#7C8DB5", textAlign: "center", marginTop: 30 },
});
