import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050E1D",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.26)",
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logo: {
    width: 100,
    height: 80,
  },
  notification: {
    position: "relative",
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: -4,
    right: 2,
    backgroundColor: "#ff4757",
    borderRadius: 8,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "bold",
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
    marginTop: 8,
  },
  contentArea: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 60,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  label: {
    color: "#7C8DB5",
    fontSize: 13,
    marginBottom: 6,
    fontWeight: "500",
  },
  input: {
    backgroundColor: "#101D33",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(22, 199, 231, 0.25)",
    color: "#FFFFFF",
    paddingHorizontal: 14,
    height: 48,
    marginBottom: 16,
    fontSize: 15,
  },
  textArea: {
    height: 90,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  flexField: {
    flex: 1,
  },
  pickerFake: {
    backgroundColor: "#101D33",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(22, 199, 231, 0.25)",
    height: 48,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  pickerFakeText: {
    color: "#FFFFFF",
    fontSize: 15,
  },
  rowDisciplinas: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  inputInline: {
    backgroundColor: "#101D33",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(22, 199, 231, 0.25)",
    color: "#FFFFFF",
    paddingHorizontal: 14,
    height: 44,
    fontSize: 15,
    marginBottom: 0,
  },
  btnAdicionar: {
    backgroundColor: "#16C7E7",
    height: 44,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
    alignSelf: "flex-end",
  },
  btnAdicionarText: {
    color: "#050E1D",
    fontSize: 14,
    fontWeight: "bold",
  },
  listaDisciplinasContainer: {
    backgroundColor: "#0B1526",
    borderRadius: 8,
    padding: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  itemDisciplina: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.05)",
  },
  itemDisciplinaNome: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  itemDisciplinaCarga: {
    color: "#7C8DB5",
    fontSize: 12,
    marginTop: 2,
  },
  btnLancar: {
    backgroundColor: "#16C7E7",
    height: 52,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  btnLancarText: {
    color: "#050E1D",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
});
