import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050E1D",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.26)",
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logo: {
    width: 100,
    height: 80,
  },
  notification: {
    position: "relative",
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: -4,
    right: 2,
    backgroundColor: "#ff4757",
    borderRadius: 8,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "bold",
  },
  content: {
    padding: 16,
    paddingBottom: 48,
  },
  title: {
    color: "#FFF",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 23,
  },
  subtitle: {
    color: "#7c8db5",
    fontSize: 14,
    marginBottom: 35,
  },

  card: {
    backgroundColor: "#10213E",
    borderRadius: 14,
    padding: 16,
  },
  label: {
    color: "#A8B3CF",
    fontSize: 13,
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    backgroundColor: "#223654",
    borderRadius: 10,
    padding: 13,
    color: "#FFF",
    fontSize: 14,
  },
  select: {
    backgroundColor: "#223654",
    borderRadius: 10,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selectPlaceholder: {
    color: "#7c8db5",
    fontSize: 14,
    flex: 1,
  },
  selectValue: {
    color: "#FFF",
    fontSize: 14,
    flex: 1,
  },
  loadingSelect: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#223654",
    borderRadius: 10,
    padding: 13,
  },
  loadingText: {
    color: "#7c8db5",
    fontSize: 14,
  },

  usuarioSelecionadoContainer: {
    marginTop: 10,
    backgroundColor: "#0d2040",
    borderRadius: 12,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#16C7E7",
  },
  avatarCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#16C7E7",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  avatarInitial: {
    color: "#050E1D",
    fontWeight: "700",
  },

  button: {
    marginTop: 20,
    backgroundColor: "#16C7E7",
    paddingVertical: 14,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    fontWeight: "700",
    fontSize: 15,
    color: "#050E1D",
  },

  sectionTitle: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "700",
    marginTop: 28,
    marginBottom: 12,
  },
  turmaCard: {
    backgroundColor: "#10213E",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderLeftWidth: 3,
    borderLeftColor: "#16C7E7",
  },
  turmaHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  turmaNome: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "700",
    flex: 1,
  },
  badge: {
    backgroundColor: "#0d3d2e",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  turmaInfo: {
    color: "#A8B3CF",
    fontSize: 13,
    marginTop: 2,
  },
  turmaId: {
    color: "#4a5f7a",
    fontSize: 11,
    marginTop: 4,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#10213E",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    height: "75%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "700",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#223654",
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: "#FFF",
    paddingVertical: 12,
    fontSize: 14,
  },
  emptyText: {
    color: "#7c8db5",
    textAlign: "center",
    marginTop: 24,
  },

  usuarioItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#1a2f4e",
    gap: 12,
  },
  usuarioItemSelected: {
    backgroundColor: "#0d2040",
    borderRadius: 10,
    paddingHorizontal: 8,
  },
  usuarioAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#16C7E7",
    alignItems: "center",
    justifyContent: "center",
  },
  usuarioAvatarText: {
    color: "#050E1D",
    fontWeight: "700",
    fontSize: 16,
  },
  usuarioNome: {
    color: "#FFF",
    fontWeight: "600",
    fontSize: 14,
  },
  usuarioEmail: {
    color: "#7c8db5",
    fontSize: 12,
    marginTop: 2,
  },
});
