import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050E1D",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logo: {
    width: 100,
    height: 80,
    resizeMode: "contain",
  },
  notification: {
    position: "relative",
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#ff4757",
    borderRadius: 8,
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "bold",
  },
  contentArea: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  gridInformativo: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 24,
  },
  cardInfo: {
    width: "48%",
    backgroundColor: "#0B1526",
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    minHeight: 110,
    justifyContent: "space-between",
  },
  cardValor: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "bold",
    marginTop: 8,
  },
  cardLabel: {
    color: "#7C8DB5",
    fontSize: 13,
  },
  titleAcoes: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 14,
  },
  gridAcoes: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 28,
  },
  btnAcao: {
    flex: 1,
    backgroundColor: "#0B1526",
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
    height: 90,
    justifyContent: "space-between",
  },
  labelAcao: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  verTodosText: {
    color: "#16C7E7",
    fontSize: 14,
    fontWeight: "600",
  },
  cursoCard: {
    backgroundColor: "#0B1526",
    borderRadius: 14,
    padding: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#101D33",
  },
  cursoInfoContainer: {
    flex: 1,
    paddingRight: 8,
  },
  cursoNome: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 6,
  },
  cursoDetalhes: {
    color: "#7C8DB5",
    fontSize: 13,
  },
  badgeAtivo: {
    backgroundColor: "rgba(46, 213, 115, 0.15)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  badgeTextActive: {
    color: "#2ed573",
    fontSize: 12,
    fontWeight: "700",
  },
});
