spring.application.name=Questio Backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/questio_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false

springdoc.swagger-ui.path=/swagger-ui.html

api.security.token.secret=9408c4805b99db82ac6be860b844e642ab29d9fdc0eff744a51f66c36821400415d158336d039b947034088405f1c92b99117aa30e8179c89944a30279c5e67a