-- Corrige a tabela eventos
ALTER TABLE eventos
ALTER COLUMN data_evento TYPE TIMESTAMP USING data_evento::TIMESTAMP,
  ADD COLUMN IF NOT EXISTS descricao_evento TEXT,
  ADD COLUMN IF NOT EXISTS titulo_evento VARCHAR(255),
  ADD COLUMN IF NOT EXISTS nome_professor VARCHAR(255),
  ADD COLUMN IF NOT EXISTS nome_aluno VARCHAR(255),
  ADD COLUMN IF NOT EXISTS id_professor UUID,
  ADD COLUMN IF NOT EXISTS id_aluno UUID,
  ADD COLUMN IF NOT EXISTS turma VARCHAR(255),
  ADD COLUMN IF NOT EXISTS semestre VARCHAR(255),
  ADD COLUMN IF NOT EXISTS tipo VARCHAR(255),
  ADD COLUMN IF NOT EXISTS lido BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
  ADD COLUMN IF NOT EXISTS disciplina VARCHAR(255);