spring.application.name=Questio Backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/questio_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.swagger-ui.path=/swagger-ui.html

api.security.token.secret=9408c4805b99db82ac6be860b844e642ab29d9fdc0eff744a51f66c36821400415d158336d039b947034088405f1c92b99117aa30e8179c89944a30279c5e67a

app.frontend.url:http://localhost:8081

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=joaoocosta161@gmail.com
spring.mail.password=SiRugUplSpm7nw!
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
