spring.application.name=Questio Backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/questio_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.swagger-ui.path=/swagger-ui.html

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:9408c4805b99db82ac6be860b844e642ab29d9fdc0eff744a51f66c36821400415d158336d039b947034088405f1c92b99117aa30e8179c89944a30279c5e67a}

app.frontend.url=${APP_FRONTEND_URL:http://localhost:8081}

spring.mail.host=${SPRING_MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${SPRING_MAIL_PORT:2525}
spring.mail.username=${SPRING_MAIL_USERNAME:joaoocosta161@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:SiRugUplSpm7nw!}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true